steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'train_model.dockerfile', '-t', 'gcr.io/mlopslfm/lfm_trainer', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mlopslfm/lfm_trainer']


  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'test_model.dockerfile', '-t', 'gcr.io/mlopslfm/lfm_tester', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mlopslfm/lfm_tester']