steps:
  - name: 'docker/compose:1.29.2'
    args:
      - '-f'
      - 'docker-compose.yaml'
      - 'build'
      - 'lfm_trainer'  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mlopslfm/lfm_trainer']  

  - name: 'docker/compose:1.29.2'
    args:
      - '-f'
      - 'docker-compose.yaml'
      - 'build'
      - 'lfm_test' 
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mlopslfm/lfm_test']  
